// <auto-generated />
using System;
using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527165316_AddHrAttendanceSettings")]
    partial class AddHrAttendanceSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_cfg_menus");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cfg_menus_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_cfg_menus_is_deleted");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_cfg_menus_module_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_cfg_menus_parent_id");

                    b.ToTable("cfg_menus", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cfg_modules");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cfg_modules_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cfg_modules_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_cfg_modules_is_deleted");

                    b.ToTable("cfg_modules", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cfg_roles");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cfg_roles_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_cfg_roles_is_deleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_cfg_roles_name");

                    b.ToTable("cfg_roles", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgRoleMenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_create");

                    b.Property<bool>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_edit");

                    b.Property<bool>("CanView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_view");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_cfg_role_menu_permissions");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_cfg_role_menu_permissions_menu_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_cfg_role_menu_permissions_role_id");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_cfg_role_menu_permissions_role_id_menu_id");

                    b.ToTable("cfg_role_menu_permissions", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrAttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CheckIn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("check_in");

                    b.Property<DateTimeOffset?>("CheckOut")
                        .HasColumnType("timestamptz")
                        .HasColumnName("check_out");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_attendance_records");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_attendance_records_created_at");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_hr_attendance_records_date");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_hr_attendance_records_employee_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_attendance_records_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hr_attendance_records_status");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_attendance_records_employee_id_date");

                    b.ToTable("hr_attendance_records", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrAttendanceSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendancePeriod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attendance_period");

                    b.Property<TimeOnly>("BreakEnd")
                        .HasColumnType("time")
                        .HasColumnName("break_end");

                    b.Property<TimeOnly>("BreakStart")
                        .HasColumnType("time")
                        .HasColumnName("break_start");

                    b.Property<int>("CheckInToleranceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("check_in_tolerance_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("LateToleranceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("late_tolerance_minutes");

                    b.Property<int>("MinimumOtMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("minimum_ot_minutes");

                    b.Property<string>("SingletonKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("default")
                        .HasColumnName("singleton_key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("time")
                        .HasColumnName("work_end");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("time")
                        .HasColumnName("work_start");

                    b.HasKey("Id")
                        .HasName("pk_hr_attendance_settings");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_attendance_settings_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_attendance_settings_is_deleted");

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_attendance_settings_singleton_key");

                    b.ToTable("hr_attendance_settings", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_department_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_departments");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_departments_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_departments_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_departments_is_deleted");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_hr_departments_manager_id");

                    b.HasIndex("ParentDepartmentId")
                        .HasDatabaseName("ix_hr_departments_parent_department_id");

                    b.ToTable("hr_departments", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employee_code");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("employment_status");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("termination_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hr_employees");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_employees_created_at");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_hr_employees_department_id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_employees_employee_code");

                    b.HasIndex("EmploymentStatus")
                        .HasDatabaseName("ix_hr_employees_employment_status");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_employees_is_deleted");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_hr_employees_position_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hr_employees_user_id");

                    b.ToTable("hr_employees", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrLeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer")
                        .HasColumnName("total_days");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_leave_requests");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_hr_leave_requests_approved_by");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_leave_requests_created_at");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_hr_leave_requests_employee_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_leave_requests_is_deleted");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("ix_hr_leave_requests_leave_type_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hr_leave_requests_status");

                    b.ToTable("hr_leave_requests", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrLeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCarryOver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_carry_over");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("integer")
                        .HasColumnName("max_days_per_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_leave_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_leave_types_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_leave_types_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_leave_types_is_deleted");

                    b.ToTable("hr_leave_types", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPayrollDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allowances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("allowances");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("basic_salary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Deductions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("deductions");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_salary");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_salary");

                    b.Property<int>("PayrollRunId")
                        .HasColumnType("integer")
                        .HasColumnName("payroll_run_id");

                    b.Property<decimal>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_payroll_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_payroll_details_created_at");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_hr_payroll_details_employee_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_payroll_details_is_deleted");

                    b.HasIndex("PayrollRunId")
                        .HasDatabaseName("ix_hr_payroll_details_payroll_run_id");

                    b.HasIndex("PayrollRunId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_payroll_details_payroll_run_id_employee_id");

                    b.ToTable("hr_payroll_details", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPayrollRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer")
                        .HasColumnName("period_month");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_year");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("integer")
                        .HasColumnName("processed_by");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_payroll_runs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_payroll_runs_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_payroll_runs_is_deleted");

                    b.HasIndex("ProcessedBy")
                        .HasDatabaseName("ix_hr_payroll_runs_processed_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hr_payroll_runs_status");

                    b.HasIndex("PeriodMonth", "PeriodYear")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_payroll_runs_period_month_period_year");

                    b.ToTable("hr_payroll_runs", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_hr_positions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_positions_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hr_positions_created_at");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_hr_positions_department_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_hr_positions_is_deleted");

                    b.ToTable("hr_positions", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_sys_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_sys_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_sys_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sys_audit_logs_user_id");

                    b.ToTable("sys_audit_logs", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sys_refresh_tokens_user_id");

                    b.ToTable("sys_refresh_tokens", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguagePreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("language_preference");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_sys_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_sys_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_sys_users_is_deleted");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_users_username");

                    b.ToTable("sys_users", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_sys_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sys_user_roles_user_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_user_roles_user_id_role_id");

                    b.ToTable("sys_user_roles", "public");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgMenu", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Config.CfgModule", "Module")
                        .WithMany("Menus")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cfg_menus_cfg_modules_module_id");

                    b.HasOne("ERP.Domain.Entities.Config.CfgMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cfg_menus_cfg_menus_parent_id");

                    b.Navigation("Module");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgRoleMenuPermission", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Config.CfgMenu", "Menu")
                        .WithMany("RoleMenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cfg_role_menu_permissions_cfg_menus_menu_id");

                    b.HasOne("ERP.Domain.Entities.Config.CfgRole", "Role")
                        .WithMany("RoleMenuPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cfg_role_menu_permissions_cfg_roles_role_id");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrAttendanceRecord", b =>
                {
                    b.HasOne("ERP.Domain.Entities.HR.HrEmployee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_attendance_records_hr_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrDepartment", b =>
                {
                    b.HasOne("ERP.Domain.Entities.HR.HrEmployee", "Manager")
                        .WithMany("DepartmentsAsManager")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hr_departments_hr_employees_manager_id");

                    b.HasOne("ERP.Domain.Entities.HR.HrDepartment", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hr_departments_hr_departments_parent_department_id");

                    b.Navigation("Manager");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrEmployee", b =>
                {
                    b.HasOne("ERP.Domain.Entities.HR.HrDepartment", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hr_employees_hr_departments_department_id");

                    b.HasOne("ERP.Domain.Entities.HR.HrPosition", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hr_employees_hr_positions_position_id");

                    b.HasOne("ERP.Domain.Entities.System.SysUser", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hr_employees_sys_users_user_id");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrLeaveRequest", b =>
                {
                    b.HasOne("ERP.Domain.Entities.System.SysUser", "ApprovedByUser")
                        .WithMany("ApprovedLeaveRequests")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hr_leave_requests_sys_users_approved_by");

                    b.HasOne("ERP.Domain.Entities.HR.HrEmployee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hr_leave_requests_hr_employees_employee_id");

                    b.HasOne("ERP.Domain.Entities.HR.HrLeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hr_leave_requests_hr_leave_types_leave_type_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPayrollDetail", b =>
                {
                    b.HasOne("ERP.Domain.Entities.HR.HrEmployee", "Employee")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hr_payroll_details_hr_employees_employee_id");

                    b.HasOne("ERP.Domain.Entities.HR.HrPayrollRun", "PayrollRun")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_payroll_details_hr_payroll_runs_payroll_run_id");

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPayrollRun", b =>
                {
                    b.HasOne("ERP.Domain.Entities.System.SysUser", "ProcessedByUser")
                        .WithMany("ProcessedPayrollRuns")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hr_payroll_runs_sys_users_processed_by");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPosition", b =>
                {
                    b.HasOne("ERP.Domain.Entities.HR.HrDepartment", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hr_positions_hr_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysRefreshToken", b =>
                {
                    b.HasOne("ERP.Domain.Entities.System.SysUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_refresh_tokens_sys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysUserRole", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Config.CfgRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_user_roles_cfg_roles_role_id");

                    b.HasOne("ERP.Domain.Entities.System.SysUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_user_roles_sys_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenuPermissions");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgModule", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Config.CfgRole", b =>
                {
                    b.Navigation("RoleMenuPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrDepartment", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrEmployee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("DepartmentsAsManager");

                    b.Navigation("LeaveRequests");

                    b.Navigation("PayrollDetails");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrLeaveType", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPayrollRun", b =>
                {
                    b.Navigation("PayrollDetails");
                });

            modelBuilder.Entity("ERP.Domain.Entities.HR.HrPosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Domain.Entities.System.SysUser", b =>
                {
                    b.Navigation("ApprovedLeaveRequests");

                    b.Navigation("Employees");

                    b.Navigation("ProcessedPayrollRuns");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
