version: '3.9'

services:

  erp-redis:
    ports:
      - "6379:6379"

  erp-pgadmin:
    image: dpage/pgadmin4
    container_name: erp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@erp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - erp_network

  erp-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  erp-web:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
